### ISSUE TITLE
New Platform Initiate

### ISSUE THREAD

**Issue by RobertBColton** [Velocity-/jWakfu#4]
Yes hello you are the god coder.

**Comment by Velocity-** [comment]
Yes he is. He is the one and only God himself. Some refer to him as the 'God Coder'.

For real though, what's up sir?

**Comment by RobertBColton** [comment]
@Velocity- I am a Java coder, like you. I was wondering if you've ever done any game development and would be interested in chatting some more over IRC? I am also interested to know if you currently have a girlfriend?

**Comment by Velocity-** [comment]
@RobertBColton I currently do have a girlfriend but she doesn't know yet.
I don't really use IRC much but if you've got a spot where I can find you I'll hit you up sometime today.

**Comment by RobertBColton** [comment]
@Velocity- She's a lucky girl for sure :smile_cat: 

Hit us up on #enigma-dev on freenode sometime:
http://webchat.freenode.net/?channels=enigma&uio=d4

One of my prior games includes a Mario clone:
https://www.youtube.com/watch?v=JsI1PbEuqfo
